version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update 
      - run: sudo apt install ruby-full
      - run: ruby --version


workflows:
  build:
    jobs:
      - build
    
