version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.5
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update 
     # - run: sudo apt install ruby-full
      - run: ruby --version


workflows:
  build:
    jobs:
      - build
    
